### ISSUE TITLE
Not work url without extension 

### ISSUE THREAD

**Issue by Base2526** [sahasbhop/apng-view#13]
Not work url without extension : (ex. http://128.199.95.80/sites/default/files/A9041AB7916E493C6381F96B5EE29C3D)
Log
sendRequest>>
08-06 23:28:20.744 5633-6372/com.github.sahasbhop.apngview.sample I/System.out: [OkHttp] sendRequest<<
08-06 23:28:21.070 5633-5633/com.github.sahasbhop.apngview.sample D/FeatureProxyBase: FeatureProxyBase class constructor
08-06 23:28:21.070 5633-5633/com.github.sahasbhop.apngview.sample D/MultiWindow: MultiWindowProxy constructor.
08-06 23:28:21.070 5633-5633/com.github.sahasbhop.apngview.sample D/FeatureProxyBase: getService(), serviceName = multiwindow_service_v1
08-06 23:28:21.154 5633-5633/com.github.sahasbhop.apngview.sample V/SettingsInterface:  from settings cache , name = sound_effects_enabled , value = 0
08-06 23:28:21.154 5633-5633/com.github.sahasbhop.apngview.sample V/ImageFragment$1: onClick # Start animation
08-06 23:28:22.176 5633-5633/com.github.sahasbhop.apngview.sample I/Choreographer: Skipped 62 frames!  The application may be doing too much work on its main thread.
08-06 23:28:22.178 5633-5710/com.github.sahasbhop.apngview.sample D/Surface: Surface::setBuffersDimensions(this=0xb45a6400,w=540,h=960)
08-06 23:28:22.183 5633-5633/com.github.sahasbhop.apngview.sample W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.github.sahasbhop.apngview.sample/cache
08-06 23:28:22.185 5633-6365/com.github.sahasbhop.apngview.sample I/System.out: open:http://128.199.95.80/sites/default/files/A9041AB7916E493C6381F96B5EE29C3D
08-06 23:28:22.186 5633-6365/com.github.sahasbhop.apngview.sample D/libc-netbsd: [getaddrinfo]: hostname=128.199.95.80; servname=(null); cache_mode=(null), netid=0; mark=0
08-06 23:28:22.186 5633-6365/com.github.sahasbhop.apngview.sample D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
08-06 23:28:22.186 5633-6365/com.github.sahasbhop.apngview.sample I/System.out: [CDS]rx timeout:20000
08-06 23:28:22.186 5633-6365/com.github.sahasbhop.apngview.sample I/System.out: [OkHttp] sendRequest>>
08-06 23:28:22.186 5633-6365/com.github.sahasbhop.apngview.sample I/System.out: [OkHttp] sendRequest<<
08-06 23:28:22.284 5633-6365/com.github.sahasbhop.apngview.sample E/ImageLoader: /data/data/com.github.sahasbhop.apngview.sample/cache/uil-images/1515367486.0: open failed: ENOENT (No such file or directory)
                                                                                 java.io.FileNotFoundException: /data/data/com.github.sahasbhop.apngview.sample/cache/uil-images/1515367486.0: open failed: ENOENT (No such file or directory)
                                                                                     at libcore.io.IoBridge.open(IoBridge.java:496)
                                                                                     at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                                                     at java.io.FileInputStream.<init>(FileInputStream.java:103)
                                                                                     at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromFile(BaseImageDownloader.java:180)
                                                                                     at com.github.sahasbhop.apngview.assist.ApngImageDownloader.getStreamFromFile(ApngImageDownloader.java:50)
                                                                                     at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:90)
                                                                                     at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.getImageStream(BaseImageDecoder.java:98)
                                                                                     at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:74)
                                                                                     at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:265)
                                                                                     at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:238)
                                                                                     at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                     at libcore.io.Posix.open(Native Method)
                                                                                     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                                     at libcore.io.IoBridge.open(IoBridge.java:482)

thx.

**Comment by cheskos** [comment]
Author said he is no longer maintaining this in another issue :( 
Good luck
