### ISSUE TITLE
数组越界

### ISSUE THREAD

**Issue by xjtn8gl** [sahasbhop/apng-view#22]
java.lang.IndexOutOfBoundsException: Invalid index 25, size is 25
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.github.sahasbhop.apngview.ApngDrawable.createAnimateBitmap(ApngDrawable.java:342)
        at com.github.sahasbhop.apngview.ApngDrawable.drawAnimateBitmap(ApngDrawable.java:313)
        at com.github.sahasbhop.apngview.ApngDrawable.draw(ApngDrawable.java:229)
        at android.widget.ImageView.onDraw(ImageView.java:1226)
        at android.view.View.draw(View.java:16256)
        at android.view.View.updateDisplayListIfDirty(View.java:15253)
        at android.view.View.draw(View.java:16026)

他报这个错误的时候，前面还有个错误说是找不到文件
E2C5859598AAE6C0E42B857B90B6567C_025.png: open failed: ENOENT (No such file or directory)

我不知道这是什么原因，可以看一下吗

**Comment by xjtn8gl** [comment]
出现这个数组越界，是因为我频繁的关开view，然后重置APNG的位置，导致的这个数组越界
